### PR TITLE
Upgrade aws-sdk to v3

### PR DESCRIPTION
**Pull request by unasuke**
use aws-sdk-s3 gem instead of aws-sdk-core gem

### CODE REVIEW

**Comment by ksss** [comment]
Thank you for improving ❤️

**Comment by ksss** [comment]
@unasuke I added you to collaborator in github and rubygems.
Could you release v0.7.2 for confirmation?

```
$ bundle exec rake release
```

**Comment by unasuke** [comment]
Sure! 🙆

**Comment by unasuke** [comment]
released successfully!

https://rubygems.org/gems/tori

**Comment by ksss** [comment]
❤️

**Pull request merged**
